name: cpu-build

on:
  push:
    paths-ignore: 
      - 'README.md'
      - '.github/**' 
      - 'docs/**'
      - 'apps/examples/KSC/docs/**'  
      - '*.yml'
    branches:
      - master
  pull_request:
    paths-ignore: 
      - 'README.md'
      - '.github/**'
      - 'docs/**'
      - 'apps/examples/KSC/docs/**'  
      - '*.yml'      
    branches: 
      - master

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # set up the os and compiler combinations to test 
      matrix:
        # populate the .name matrix 
        name: [
          ubuntu-20.04-gcc-9,
          ubuntu-18.04-gcc-8,
          ubuntu-18.04-gcc-7,
          macOS-10.15-gcc-9,
          macOS-10.15-gcc-8,
          macOS-10.15-xcode-11.6,
          macOS-10.15-xcode-latest-stable,
        ]
        # populate the .os matrix  
        include:
            ## Ubuntu + gcc
          - name: ubuntu-20.04-gcc-9  
            os: ubuntu-20.04
            compiler: gcc
            version: "9"

          - name: ubuntu-18.04-gcc-8  
            os: ubuntu-18.04
            compiler: gcc
            version: "8"

          - name: ubuntu-18.04-gcc-7  
            os: ubuntu-18.04
            compiler: gcc
            version: "7"

            ## MacOS + gcc
          - name: macOS-10.15-gcc-9  
            os: macOS-10.15
            compiler: gcc
            version: "9"

          - name: macOS-10.15-gcc-8  
            os: macOS-10.15
            compiler: gcc
            version: "8"

            ## MacOS + clang            
          - name: macOS-10.15-xcode-11.6  
            os: macOS-10.15
            compiler: xcode
            version: "11.6"

          - name: macOS-10.15-xcode-11.1  
            os: macOS-10.15
            compiler: xcode
            version: "latest-stable"


    steps:
      - uses: actions/checkout@v2

      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          # it's always gcc compiler in case of Linux so just protect for future
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
               sudo apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib
               echo "::set-env name=CC::gcc-${{ matrix.version }}"
               echo "::set-env name=CXX::g++-${{ matrix.version }}"
          fi

      - name: Install (MacOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake ninja

          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            brew install gcc@${{ matrix.version }}
            echo "::set-env name=CC::gcc-${{ matrix.version }}"
            echo "::set-env name=CXX::g++-${{ matrix.version }}"
          else
            sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
            echo "::set-env name=CC::clang"
            echo "::set-env name=CXX::clang++"
          fi

      - name: Build & Test Debug
        run: |
          cmake -E remove_directory build
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON
          cmake --build build
          cd build && ctest -j2 --verbose --output-on-failure

      - name: Build & Test Release
        run: |
          cmake -E remove_directory build
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
          cmake --build build
          cd build && ctest -j2 --verbose --output-on-failure

