# builds only since there is no device
name: CUDA-ubuntu-build

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'docs/**'
      - 'apps/examples/KSC/docs/**'
      - '*.yml'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'docs/**'
      - 'apps/examples/KSC/docs/**'
      - '*.yml'
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            cuda: "12.2.0"
            gcc: 11

          - os: ubuntu-22.04
            cuda: "12.3.2"
            gcc: 12

    env:
      build_dir: "build"

    steps:
    - uses: actions/checkout@v4

    - name: Install CUDA
      uses: Jimver/cuda-toolkit@v0.2.24
      with:
        cuda: ${{ matrix.cuda }}
        method: network
        sub-packages: '["nvcc", "cudart", "cublas", "cublas-dev"]'

    - name: Install/Select gcc and g++
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-${{ matrix.gcc }} \
          g++-${{ matrix.gcc }} \
          gfortran-${{ matrix.gcc }} \
          libblas-dev \
          liblapack-dev

        echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
        echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
        echo "FC=/usr/bin/gfortran-${{ matrix.gcc }}" >> $GITHUB_ENV
        echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV

    - name: Show CUDA/compiler versions
      run: |
        which nvcc
        nvcc --version
        ${CC} --version
        ${CXX} --version
        ${FC} --version

    - name: Configure cmake (Debug)
      id: configure
      run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=Debug -DUSE_CUBLAS=ON -DBUILD_TESTS=ON

    - name: Configure Error Processing
      if: ${{ failure() && steps.configure.outcome == 'failure' }}
      working-directory: ${{ env.build_dir }}
      run: |
          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
            echo "---- CMakeFiles/CMakeOutput.log"
            cat CMakeFiles/CMakeOutput.log
            echo "----"
          fi
          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
            echo "---- CMakeFiles/CMakeError.log"
            cat CMakeFiles/CMakeError.log
            echo "----"
          fi

    - name: Build (Debug)
      working-directory: ${{ env.build_dir }}
      run: cmake --build . --target all --verbose -j `nproc`
